# Generated by Django 3.1.7 on 2021-08-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storygraph", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="position",
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
