# Generated by Django 3.1.7 on 2021-08-22 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storygraph", "0002_node_add_unique_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datablock",
            name="link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_block",
                to="storygraph.link",
            ),
        ),
    ]
