# Generated by Django 3.1.7 on 2021-08-22 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storygraph", "0003_rename_related_name_on_data_block_link_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datablock",
            name="link",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_block",
                to="storygraph.link",
            ),
        ),
    ]
