# Generated by Django 3.1.7 on 2021-08-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storygraph", "0004_change_data_block_link_from_fk_to_one_to_one"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="node",
            name="title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
