# Generated by Django 3.1.7 on 2021-08-23 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storygraph", "0005_add_title_and_body_to_node"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="nextNode",
            new_name="next_node",
        ),
        migrations.AlterField(
            model_name="link",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="storygraph.node",
            ),
        ),
    ]
