# Generated by Django 3.1.7 on 2021-09-10 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storygraph", "0010_provide_initial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="next_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_choice",
                to="storygraph.node",
            ),
        ),
    ]
